[General]
# this section only has one instance and therefore no name

# Logging verbosity (stderr)
# Valid values: <error>, <warning>, <info> or <debug>
# Default: <info>
DebugLogLevel = info

# Enable de-duplication of incoming messages. If a message is received another
# time in the configured time period (in milliseconds), it will be dropped. The
# second message will reset the timer.
# It should be a bit higher, than the latency of the slowest link. More than
# 1000 ms might drop packets unintentionally though.
# Default: 0 (de-duplication disabled)
DeDuplicationPeriod = 0

## TCP Server Endpoints - Disable
# Listen for TCP connections on this port. Set to 0 to disable.
# Default: 5760
TcpServerPort = 0


## GCS Port Modem
[UdpEndpoint port_modem]
Mode = Server
Address = 0.0.0.0
Port = 15000
Group = gcs_modems
AllowSrcSysIn = 1

## GCS Stbd Modem ##
#[UdpEndpoint stbd_modem]
# Mode = Server
# Address = 0.0.0.0
# Port = 15002
# Group = gcs_modems
# AllowSrcSysIn = 1

## GCS Port Diagnostics
[UdpEndpoint port_boost]
Mode = Normal
Address = 192.168.2.70
Port = 15001

## GCS Stbd Diagnostics ##
#[UdpEndpoint stbd_boost]
# Mode = Normal
# Address = 192.168.2.70
# Port = 15003


## UDP
# Lockhead Martin Panel
[UdpEndpoint vcsi_lhm]
Mode = Normal
Address = 192.168.2.220
Port = 14550
Group = gcs

# LZC Custom Panels
[UdpEndpoint vcsi_lzc]
Mode = Normal
Address = 192.168.2.220
Port = 14560
Group = gcs

# Mission Planner
[UdpEndpoint mp_gcs]
Mode = Normal
Address = 192.168.2.220
Port = 14570
Group = gcs
#BlockMsgIdIn = 0 # Heartbeat

# SATPRO Antenna Tracker
[UdpEndpoint tracker]
Mode = Normal
Address = 192.168.2.80
Port = 8002
AllowMsgIdOut = 24  #Only GPS_RAW_INT
Group = gcs

# SuperWake Monitor
[UdpEndpoint sw_listen]
Mode = Normal
Address = 15.223.44.65
Port = 10099
Group = gcs
BlockMsgIdIn = 0, 11, 76  # Dual layer security..

# Listen only GCS setup
[UdpEndpoint vcsi_listen]
Mode = Normal
Address = 192.168.2.224
Port = 14550
AllowMsgIdIn = 20,76  # Needed for initial LHM connection
Group = gcs

# Simulated Wind Port
# [UdpEndpoint sim_wind_gcs]
# Mode = Normal
# Address = 192.168.2.220
# Port = 14590
# Group = gcs
